[package]
name = "cdoc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "cdoc"
path = "src/lib.rs"

[dependencies]
# Serialization
serde = "1.0.150"
serde_json = "1.0.89"
serde_yaml = "0.9.14"
serde_with = "2.1.0"
toml = "0.5.10"
typetag = "0.2.3"

# Parsing / formatting
yaml-front-matter = "0.1.0"
tera = "1.17.1"
pulldown-cmark = "0.9.2"
pulldown-cmark-to-cmark = "10.0.4"
base64 = "0.20.0"
katex = "0.4.5"
pest = "2.5.1"
pest_derive = "2.5.1"

# Utilities
thiserror = "1.0.37"
anyhow = "1.0.66"

clap = {version="4.0.29", optional=true}

[features]
build-binary = ["clap"]
