[package]
name = "courses"
version = "0.1.0"
edition = "2021"

[lib]
name = "courses"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.145", features = ["derive", "rc"]}
serde_yaml = "0.9.13"
serde_json = "1.0.85"
serde_with = "2.0.1"

base64 = "0.13.1"
image = "0.24.4"
indicatif = "0.17.2"
yaml-front-matter = "0.1.0"

tempfile = "3.3.0"
relative-path = "1.7.2"
rust-embed = "6.4.2"
inquire = "0.5.2"

termion = "2.0.1"

thiserror = "1.0.37"
anyhow = { version = "1.0.65", features = ["backtrace"] }

clap = {version = "4.0.0-rc.2", features = ["derive"]}

lazy_static = "1.4.0"

pest = "2.3.1"
pest_derive = "2.3.1"
pandoc = "0.8.10"
tera = "1.17.1"

pulldown-cmark = "0.9.2"

enum_dispatch = "0.3.8"

notify = {version="5.0.0"}
notify-debouncer-mini = "0.2.1"

penguin = "0.1.7"
tokio = {version="1.21.2", features=["full"]}