[package]
name = "courses"
version = "0.1.1"
edition = "2021"
license = "GPL-3.0-or-later"

authors = ["Anton Mølbjerg Eskildsen"]

description = "A publishing system for interactive content"

homepage = "https://antonmeskildsen.github.io/courses/"
repository = "https://github.com/antonmeskildsen/courses"
readme = "README.md"

keywords = ["web", "ssg", "publishing", "notebooks", "education"]
categories = ["web-programming", "template-engine", "command-line-utilities"]

[lib]
name = "courses"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.145", features = ["derive", "rc"]}
serde_yaml = "0.9.13"
serde_json = "1.0.85"
serde_with = "2.0.1"
toml = "0.5.9"

base64 = "0.20.0"
yaml-front-matter = "0.1.0"

tempfile = "3.3.0"
rust-embed = "6.4.2"
inquire = "0.5.2"

termion = "2.0.1"
katex = "0.4.4"

fs_extra = "1.2.0"

thiserror = { version = "1.0.37"}
anyhow = { version = "1.0.65"}

clap = {version = "4.0.0-rc.2", features = ["derive"]}

lazy_static = "1.4.0"

pest = "2.3.1"
pest_derive = "2.3.1"
tera = "1.17.1"

pulldown-cmark = "0.9.2"

notify = {version="5.0.0"}
notify-debouncer-mini = "0.2.1"

penguin = "0.1.7"
tokio = {version="1.21.2", features=["full"]}