url_prefix: /courses
katex_output: true

outputs:
  - html
  - notebook
  - info

parsers:
  html:
    settings:
      solutions: false
      notebook_outputs: true
    preprocessors:
      - type: shortcodes
      - type: katex
    event_processors:
      - type: code_split
  notebook:
    settings:
      solutions: false
      notebook_outputs: true
    preprocessors:
      - type: shortcodes
    event_processors:
      - type: code_split