name: courses-docs

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo install --path ./
          cd docs
          courses build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/web/
